language: python
python:
- '3.5'
install:
- pip install -r requirements.txt
- "python -m nltk.downloader punkt"
- "python -m nltk.downloader stopwords"
- "python -m nltk.downloader maxent_treebank_pos_tagger"
script:
- python test.py
